# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug', max_length=100),
        ),
    ]
