# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
