# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171013_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contenu',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='article',
            name='preparation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
