# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171108_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ingredients',
            new_name='contenu',
        ),
        migrations.RemoveField(
            model_name='article',
            name='preparation',
        ),
    ]
